"use client";

import { useRef, useState } from "react";
import type { Suggestion } from "@/app/api/lab-assistant/route";

// ── Local UI copy (English only – this is a hackathon tool) ──────────────────

const UI = {
  pageTitle: "AI Lab Assistant",
  pageSubtitle:
    "Paste your experiment notes, upload result data, and get safe, explained next-step suggestions — without replacing your scientific judgment.",
  disclaimer:
    "Suggestions are generated by a rule-based analysis engine. They assist — not replace — researcher judgment. Consult domain experts and institutional guidelines before acting.",

  sectionNotes: "Experiment Notes",
  labelName: "Experiment Name (optional)",
  labelNotes: "Experiment Notes",
  placeholderName: "e.g. Protein expression assay – Run 3",
  placeholderNotes:
    "Describe your experiment: hypothesis, methods, observations, variables, controls…",

  sectionData: "Result Data",
  labelCsv: "CSV / Table Data",
  placeholderCsv:
    "Paste CSV data here — first row should be column headers.\nExample:\nSample,Temperature,Yield\nA,25,0.42\nB,37,0.78",
  labelImages: "Images (optional)",
  imageButtonLabel: "Choose images",
  imageHint: "PNG, JPG, WEBP — image content is not analyzed server-side; image count guides suggestions.",

  submitLabel: "Analyse & Suggest",
  submittingLabel: "Analysing…",
  clearLabel: "Clear",
  resultsTitle: "Suggestions",
  noResults: "No suggestions generated. Try adding more detail to your notes or data.",
  errorPrefix: "Error: ",

  categories: {
    "data-quality": "Data Quality",
    repeat: "Repeat / Replicate",
    modify: "Modify Protocol",
    analyze: "Statistical Analysis",
    control: "Control Group",
    safety: "Safety",
    "next-step": "Next Step",
    documentation: "Documentation",
  } as Record<string, string>,

  confidence: {
    high: "High confidence",
    medium: "Medium confidence",
    low: "Low confidence",
  } as Record<string, string>,

  categoryColors: {
    "data-quality": "text-yellow-400 border-yellow-400/30 bg-yellow-400/10",
    repeat: "text-blue-400 border-blue-400/30 bg-blue-400/10",
    modify: "text-purple-400 border-purple-400/30 bg-purple-400/10",
    analyze: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
    control: "text-green-400 border-green-400/30 bg-green-400/10",
    safety: "text-red-400 border-red-400/30 bg-red-400/10",
    "next-step": "text-orange-400 border-orange-400/30 bg-orange-400/10",
    documentation: "text-slate-400 border-slate-400/30 bg-slate-400/10",
  } as Record<string, string>,

  confidenceColors: {
    high: "text-green-400",
    medium: "text-yellow-400",
    low: "text-slate-400",
  } as Record<string, string>,
} as const;

// ── Suggestion card ──────────────────────────────────────────────────────────

function SuggestionCard({ suggestion }: { suggestion: Suggestion }) {
  const [expanded, setExpanded] = useState(false);
  const catColor = UI.categoryColors[suggestion.category] ?? "text-muted border-edge bg-panel2";
  const confColor = UI.confidenceColors[suggestion.confidence] ?? "text-muted";

  return (
    <article className="rounded-2xl border border-edge bg-panel p-5 transition-shadow hover:shadow-md">
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2">
          <span className={`inline-flex rounded-full border px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-[0.18em] ${catColor}`}>
            {UI.categories[suggestion.category] ?? suggestion.category}
          </span>
          <span className={`text-[10px] font-semibold uppercase tracking-[0.16em] ${confColor}`}>
            {UI.confidence[suggestion.confidence] ?? suggestion.confidence}
          </span>
        </div>
        <button
          type="button"
          onClick={() => setExpanded((v) => !v)}
          aria-expanded={expanded}
          className="rounded-full border border-edge px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted hover:border-brand hover:text-text"
        >
          {expanded ? "Show less" : "Why?"}
        </button>
      </div>

      <h3 className="mt-3 font-display text-base font-semibold text-text">{suggestion.title}</h3>
      <p className="mt-2 text-sm leading-relaxed text-muted">{suggestion.suggestion}</p>

      {expanded && (
        <div className="mt-4 space-y-3">
          <div className="rounded-xl border border-edge bg-panel2 p-4">
            <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-muted">Reasoning</p>
            <p className="mt-1.5 text-sm leading-relaxed text-text">{suggestion.reasoning}</p>
          </div>
          <div className="rounded-xl border border-yellow-500/20 bg-yellow-500/5 p-4">
            <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-yellow-400">Safety Note</p>
            <p className="mt-1.5 text-sm leading-relaxed text-muted">{suggestion.safetyNote}</p>
          </div>
        </div>
      )}
    </article>
  );
}

// ── Main page ────────────────────────────────────────────────────────────────

type ApiResponse = {
  suggestions: Suggestion[];
  analysedAt: string;
  disclaimer: string;
  experimentName?: string | null;
  error?: string;
};

export default function LabAssistantPage() {
  const [experimentName, setExperimentName] = useState("");
  const [notes, setNotes] = useState("");
  const [csvData, setCsvData] = useState("");
  const [imageCount, setImageCount] = useState(0);
  const [imageNames, setImageNames] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ApiResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const resultsRef = useRef<HTMLDivElement>(null);

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files ?? []);
    setImageCount(files.length);
    setImageNames(files.map((f) => f.name));
  };

  const handleClear = () => {
    setExperimentName("");
    setNotes("");
    setCsvData("");
    setImageCount(0);
    setImageNames([]);
    setResult(null);
    setError(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await fetch("/api/lab-assistant", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ experimentName, notes, csvData, imageCount }),
      });

      const data = (await res.json()) as ApiResponse;

      if (!res.ok) {
        setError(data.error ?? `Server error ${res.status}`);
      } else {
        setResult(data);
        // Scroll to results after a short delay
        setTimeout(() => {
          resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
        }, 100);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const hasInput = notes.trim() || csvData.trim() || imageCount > 0;

  return (
    <div className="mx-auto flex w-full max-w-[1100px] flex-col gap-8 pb-16">
      {/* ── Hero ────────────────────────────────────────────────────────── */}
      <section className="rounded-3xl border border-edge bg-panel p-8">
        <div className="inline-flex items-center gap-2 rounded-full border border-edge bg-panel2 px-3 py-1">
          <span className="text-[10px] uppercase tracking-[0.22em] text-muted">Hackathon Build · AI Research Tools</span>
        </div>
        <h1 className="mt-4 font-display text-4xl text-text">{UI.pageTitle}</h1>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted">{UI.pageSubtitle}</p>
        <p className="mt-2 rounded-xl border border-yellow-500/20 bg-yellow-500/5 px-4 py-2 text-xs leading-relaxed text-yellow-400">
          ⚠ {UI.disclaimer}
        </p>
      </section>

      {/* ── Form ────────────────────────────────────────────────────────── */}
      <form onSubmit={handleSubmit} className="flex flex-col gap-6">
        {/* Notes section */}
        <section className="rounded-3xl border border-edge bg-panel p-6">
          <h2 className="font-display text-xl text-text">{UI.sectionNotes}</h2>

          <div className="mt-5 space-y-4">
            <div>
              <label htmlFor="lab-name" className="block text-[10px] font-semibold uppercase tracking-[0.18em] text-muted">
                {UI.labelName}
              </label>
              <input
                id="lab-name"
                type="text"
                value={experimentName}
                onChange={(e) => setExperimentName(e.target.value)}
                placeholder={UI.placeholderName}
                maxLength={200}
                className="mt-1.5 w-full rounded-xl border border-edge bg-panel2 px-4 py-3 text-sm text-text placeholder:text-muted/50 focus:border-brand focus:outline-none"
              />
            </div>

            <div>
              <label htmlFor="lab-notes" className="block text-[10px] font-semibold uppercase tracking-[0.18em] text-muted">
                {UI.labelNotes}
              </label>
              <textarea
                id="lab-notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder={UI.placeholderNotes}
                rows={8}
                maxLength={8000}
                className="mt-1.5 w-full rounded-xl border border-edge bg-panel2 px-4 py-3 text-sm leading-relaxed text-text placeholder:text-muted/50 focus:border-brand focus:outline-none"
              />
              <p className="mt-1 text-right text-[10px] text-muted">{notes.length} / 8 000</p>
            </div>
          </div>
        </section>

        {/* Data section */}
        <section className="rounded-3xl border border-edge bg-panel p-6">
          <h2 className="font-display text-xl text-text">{UI.sectionData}</h2>

          <div className="mt-5 space-y-4">
            <div>
              <label htmlFor="lab-csv" className="block text-[10px] font-semibold uppercase tracking-[0.18em] text-muted">
                {UI.labelCsv}
              </label>
              <textarea
                id="lab-csv"
                value={csvData}
                onChange={(e) => setCsvData(e.target.value)}
                placeholder={UI.placeholderCsv}
                rows={7}
                maxLength={50000}
                spellCheck={false}
                className="mt-1.5 w-full rounded-xl border border-edge bg-panel2 px-4 py-3 font-mono text-xs leading-relaxed text-text placeholder:text-muted/50 focus:border-brand focus:outline-none"
              />
              <p className="mt-1 text-right text-[10px] text-muted">{csvData.length} / 50 000</p>
            </div>

            <div>
              <p className="block text-[10px] font-semibold uppercase tracking-[0.18em] text-muted">{UI.labelImages}</p>
              <div className="mt-1.5 flex flex-wrap items-center gap-3">
                <label
                  htmlFor="lab-images"
                  className="cursor-pointer rounded-full border border-edge bg-panel2 px-4 py-2 text-xs font-semibold uppercase tracking-[0.16em] text-text hover:border-brand"
                >
                  {UI.imageButtonLabel}
                </label>
                <input
                  id="lab-images"
                  ref={fileInputRef}
                  type="file"
                  accept="image/png,image/jpeg,image/webp"
                  multiple
                  className="sr-only"
                  onChange={handleImageChange}
                />
                {imageCount > 0 && (
                  <span className="text-xs text-muted">
                    {imageCount} image{imageCount !== 1 ? "s" : ""} selected
                  </span>
                )}
              </div>
              {imageNames.length > 0 && (
                <ul className="mt-2 flex flex-wrap gap-2">
                  {imageNames.map((name) => (
                    <li key={name} className="rounded-lg border border-edge bg-panel2 px-2.5 py-1 text-[11px] text-muted">
                      {name}
                    </li>
                  ))}
                </ul>
              )}
              <p className="mt-1 text-[10px] text-muted">{UI.imageHint}</p>
            </div>
          </div>
        </section>

        {/* Actions */}
        <div className="flex flex-wrap gap-3">
          <button
            type="submit"
            disabled={loading || !hasInput}
            className="rounded-full bg-brand px-8 py-3 text-xs font-semibold uppercase tracking-[0.22em] text-white disabled:cursor-not-allowed disabled:opacity-50"
          >
            {loading ? UI.submittingLabel : UI.submitLabel}
          </button>
          <button
            type="button"
            onClick={handleClear}
            className="rounded-full border border-edge px-6 py-3 text-xs font-semibold uppercase tracking-[0.2em] text-text hover:border-brand"
          >
            {UI.clearLabel}
          </button>
        </div>
      </form>

      {/* ── Error state ─────────────────────────────────────────────────── */}
      {error && (
        <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-5 text-sm text-red-400">
          {UI.errorPrefix}
          {error}
        </div>
      )}

      {/* ── Results ─────────────────────────────────────────────────────── */}
      {result && (
        <section ref={resultsRef} className="scroll-mt-24 flex flex-col gap-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <h2 className="font-display text-2xl text-text">
                {UI.resultsTitle}
                {result.experimentName ? ` — ${result.experimentName}` : ""}
              </h2>
              <p className="mt-1 text-[10px] text-muted">
                {result.suggestions.length} suggestion{result.suggestions.length !== 1 ? "s" : ""} ·{" "}
                {new Date(result.analysedAt).toLocaleTimeString()}
              </p>
            </div>
          </div>

          {/* Disclaimer banner */}
          <p className="rounded-xl border border-yellow-500/20 bg-yellow-500/5 px-4 py-2.5 text-xs leading-relaxed text-yellow-400">
            ⚠ {result.disclaimer}
          </p>

          {result.suggestions.length === 0 ? (
            <p className="text-sm text-muted">{UI.noResults}</p>
          ) : (
            <div className="grid gap-4 md:grid-cols-2">
              {result.suggestions.map((s) => (
                <SuggestionCard key={s.id} suggestion={s} />
              ))}
            </div>
          )}
        </section>
      )}
    </div>
  );
}
